# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title find path
#'
#' @description creates a data.table by loading the relevant f0 info from the pitch obj
#'
#' @export
find_path2 <- function(ptst, filename) {
    .Call(`_PitchMendR_find_path2`, ptst, filename)
}

#' @export
swapFrameValue <- function(frame, i, j) {
    .Call(`_PitchMendR_swapFrameValue`, frame, i, j)
}

